### PR TITLE
add disable_spellcheck() and clear_spellcheck_markers()  methods, suggest_word_for_misspelled

### PR DESCRIPTION
**Pull request by blurymind**
also set to spellcheck only when required instead of each half second - doing that should make it drain less battery - especially with alot of text

### CODE REVIEW

**Review by swenson — APPROVED** [review]
Awesome, thanks for the contribution!

**Comment by blurymind** [comment]
hey no problem :)
I am already using it in this pull:
https://github.com/InfiniteAmmoInc/Yarn/pull/80

**Comment by swenson** [comment]
I'm glad you're finding this useful!

**Comment by blurymind** [comment]
Its now used in yarn editor to mark misspelled words. For some reason the feature wasnt fully implemented, so I picked it up and got it to work.
I needed to add the method to disable it in order to make it optional to the user.
The last method I added is now used by the context menu - to suggest possible corrections of a selected misspelled word

**Pull request merged**
